#!/bin/bash

echo "🌐 seedbasket.ai 도메인 연결 가이드"
echo "=================================="
echo ""
echo "1️⃣  Firebase Console 열기:"
echo "   https://console.firebase.google.com/project/seedbasket-342ca/hosting/sites"
echo ""
echo "2️⃣  '도메인 추가' 클릭 후 seedbasket.ai 입력"
echo ""
echo "3️⃣  소유권 확인을 위한 TXT 레코드:"
echo "   Firebase가 제공하는 TXT 레코드를 도메인 DNS에 추가"
echo ""
echo "4️⃣  소유권 확인 후 다음 A 레코드 추가:"
echo ""
echo "   Type: A"
echo "   Name: @"
echo "   Value: 151.101.1.195"
echo "   TTL: 3600"
echo ""
echo "   Type: A"
echo "   Name: @"
echo "   Value: 151.101.65.195"
echo "   TTL: 3600"
echo ""
echo "5️⃣  (선택) www 서브도메인:"
echo ""
echo "   Type: CNAME"
echo "   Name: www"
echo "   Value: seedbasket-342ca.web.app."
echo "   TTL: 3600"
echo ""
echo "📝 도메인 등록업체별 DNS 설정 위치:"
echo "   - Namecheap: Dashboard → Domain List → Manage → Advanced DNS"
echo "   - GoDaddy: My Products → DNS → Manage DNS"
echo "   - Cloudflare: DNS → Add record (Proxy는 'DNS only'로 설정!)"
echo "   - Google Domains: DNS → Custom records"
echo ""
echo "⏱️  예상 소요 시간:"
echo "   - DNS 전파: 10분 ~ 48시간 (보통 1시간 이내)"
echo "   - SSL 인증서: DNS 전파 후 자동 발급"
echo ""
echo "🔍 DNS 설정 확인:"
echo "   nslookup seedbasket.ai"
echo "   dig seedbasket.ai A"
echo ""
echo "✅ 완료되면 https://seedbasket.ai 로 접속 가능!"