#!/bin/bash

echo "GitHub Secrets 설정 가이드"
echo "========================"
echo ""
echo "1. Firebase CI 토큰 생성:"
echo "   다음 명령어를 실행하세요:"
echo "   firebase login:ci"
echo ""
echo "2. 생성된 토큰을 복사하세요"
echo ""
echo "3. GitHub 저장소로 이동:"
echo "   https://github.com/yourusername/seedbasket/settings/secrets/actions"
echo ""
echo "4. 'New repository secret' 클릭"
echo ""
echo "5. 다음 시크릿 추가:"
echo "   - Name: FIREBASE_TOKEN"
echo "   - Value: [복사한 Firebase CI 토큰]"
echo ""
echo "6. 완료!"
echo ""
echo "이제 main 브랜치에 push하면 자동으로 Firebase에 배포됩니다."